using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// One whole-scene background chunk placed in the world: which template sprite,
/// where its center sits, and its chain order.
/// </summary>
public class ScenePlacement
{
    public string  sprite;
    public Vector2 center;
    public int     order;
}

/// <summary>A branch side-street painted into a template: root on the trunk, tip at the stop.</summary>
public struct SceneArm
{
    public Vector2 root;
    public Vector2 tip;
}

/// <summary>Geometry for one planned chunk of the whole-scene route.</summary>
public class SceneChunkPlan
{
    public ScenePlacement placement;
    /// <summary>Graph vertices after the entry point, in travel order (cardinal
    /// edges only — Manhattan for Automation); the last one is the chunk's exit.</summary>
    public List<Vector2> vertices = new List<Vector2>();
    /// <summary>Parallel to <see cref="vertices"/>: true where the vertex is a 90 degree turn.</summary>
    public List<bool> corners = new List<bool>();
    /// <summary>The smooth driving path entry→exit (exclusive of the entry point,
    /// inclusive of the exit). Follows the painted curve where the template has
    /// one; used for the Manual drive/traffic polyline, NOT for graph nodes.</summary>
    public List<Vector2> drivePath = new List<Vector2>();
    /// <summary>Extra road segments covering the painted curve so off-road math
    /// hugs the art. Never become graph edges (may be diagonal).</summary>
    public List<RoadSegment> extraSegments = new List<RoadSegment>();
    public List<SceneArm> arms = new List<SceneArm>();
    public Vector2 exit;
    /// <summary>Travel direction leaving this chunk.</summary>
    public Vector2 exitHeading;
}

/// <summary>
/// Whole-scene driving background planner. Every template's road ports are
/// generated from the source art by art_src/driving/build_background.py. Each
/// template stores measured road ports, so the painted roads line up at seams
/// and the jeepney stays on asphalt.
/// </summary>
public static class SceneTemplateLibrary
{
    class Template
    {
        public string sprite;
        public Vector2 size;
        public Vector2 northPort = Invalid;
        public Vector2 southPort = Invalid;
        public Vector2 eastPort  = Invalid;
        public Vector2 westPort  = Invalid;
        /// <summary>Largest corner-arc radius (world units) between this
        /// template's perpendicular roads that stays fully on the painted
        /// asphalt — measured against the source pixels. 0 for straights.</summary>
        public float fillet;
        /// <summary>
        /// Explicit drive transitions measured/approved for this art. Each
        /// code is entry edge then exit edge, e.g. "SN" means entering from
        /// the south edge and exiting the north edge.
        /// </summary>
        public string[] allow;
        public Transition[] transitions;
    }

    class Transition
    {
        public string code;
        public Vector2 graphCorner;
        /// <summary>Template-local centerline, including both edge ports.</summary>
        public Vector2[] path;
    }

    static readonly Vector2 Invalid = new Vector2(float.NaN, float.NaN);
    const float Overlap = 0.05f;     // tiny guard overlap; generated edges are opaque and matched
    const int   NoRepeatWindow = 4;  // avoid any sprite used within the last N chunks
    /// <summary>Camera framing that keeps a normalized scene chunk wider than the viewport.</summary>
    public const float RecommendedCameraOrthoSize = 9f;

    // ---- generated by build_background.py — do not hand-edit values ----------
    static readonly Template[] Templates =
    {
        // BEGIN GENERATED TEMPLATE DATA
        new Template { sprite = "town_horizontal_0", size = new Vector2(52.250f, 52.250f), westPort = new Vector2(-26.125f, 0.354f), eastPort = new Vector2(26.125f, 0.354f), allow = new[] { "WE", "EW" }, transitions = new[] { new Transition { code = "WE", graphCorner = Vector2.zero, path = new[] { new Vector2(-26.125f, 0.354f), new Vector2(26.125f, 0.354f) } }, new Transition { code = "EW", graphCorner = Vector2.zero, path = new[] { new Vector2(26.125f, 0.354f), new Vector2(-26.125f, 0.354f) } } } },
        new Template { sprite = "town_turn_e_n_0", size = new Vector2(52.250f, 52.250f), northPort = new Vector2(0.833f, 26.125f), eastPort = new Vector2(26.125f, 1.292f), fillet = 10.00f, allow = new[] { "EN" }, transitions = new[] { new Transition { code = "EN", graphCorner = new Vector2(0.833f, 1.292f), path = new[] { new Vector2(26.125f, 1.292f), new Vector2(10.833f, 1.292f), new Vector2(8.245f, 1.632f), new Vector2(5.833f, 2.631f), new Vector2(3.762f, 4.221f), new Vector2(2.173f, 6.292f), new Vector2(1.174f, 8.703f), new Vector2(0.833f, 11.292f), new Vector2(0.833f, 26.125f) } } } },
        new Template { sprite = "town_turn_s_e_0", size = new Vector2(52.250f, 52.250f), southPort = new Vector2(-2.792f, -26.125f), eastPort = new Vector2(26.125f, 10.062f), fillet = 7.00f, allow = new[] { "SE" }, transitions = new[] { new Transition { code = "SE", graphCorner = new Vector2(-2.792f, 10.062f), path = new[] { new Vector2(-2.792f, -26.125f), new Vector2(-2.792f, 3.062f), new Vector2(-2.553f, 4.874f), new Vector2(-1.854f, 6.562f), new Vector2(-0.741f, 8.012f), new Vector2(0.708f, 9.125f), new Vector2(2.397f, 9.824f), new Vector2(4.208f, 10.062f), new Vector2(26.125f, 10.062f) } } } },
        new Template { sprite = "town_turn_s_w_1", size = new Vector2(52.250f, 52.250f), southPort = new Vector2(0.667f, -26.125f), westPort = new Vector2(-26.125f, 8.125f), fillet = 9.00f, allow = new[] { "SW" }, transitions = new[] { new Transition { code = "SW", graphCorner = new Vector2(0.667f, 8.125f), path = new[] { new Vector2(0.667f, -26.125f), new Vector2(0.667f, -0.875f), new Vector2(0.360f, 1.454f), new Vector2(-0.539f, 3.625f), new Vector2(-1.969f, 5.489f), new Vector2(-3.833f, 6.919f), new Vector2(-6.004f, 7.818f), new Vector2(-8.333f, 8.125f), new Vector2(-26.125f, 8.125f) } } } },
        new Template { sprite = "town_turn_w_n_1", size = new Vector2(52.250f, 52.250f), northPort = new Vector2(3.979f, 26.125f), westPort = new Vector2(-26.125f, 0.917f), fillet = 12.50f, allow = new[] { "WN" }, transitions = new[] { new Transition { code = "WN", graphCorner = new Vector2(3.979f, 0.917f), path = new[] { new Vector2(-26.125f, 0.917f), new Vector2(-7.365f, 0.917f), new Vector2(-4.429f, 1.303f), new Vector2(-1.693f, 2.436f), new Vector2(0.657f, 4.239f), new Vector2(2.459f, 6.589f), new Vector2(3.593f, 9.324f), new Vector2(3.979f, 12.260f), new Vector2(3.979f, 26.125f) } } } },
        new Template { sprite = "town_vertical_0", size = new Vector2(52.250f, 52.250f), northPort = new Vector2(0.000f, 26.125f), southPort = new Vector2(0.000f, -26.125f), allow = new[] { "SN" }, transitions = new[] { new Transition { code = "SN", graphCorner = Vector2.zero, path = new[] { new Vector2(0.000f, -26.125f), new Vector2(0.000f, 26.125f) } } } },
        // END GENERATED TEMPLATE DATA
    };

    static bool? _active;

    /// <summary>True when the whole-scene templates exist under Resources/Driving/Background.</summary>
    public static bool Active
    {
        get
        {
            if (_active == null)
                _active = Resources.Load<Sprite>("Driving/Background/town_vertical_0") != null;
            return _active.Value;
        }
    }

    /// <summary>World size of a template sprite (streaming/AABB math).</summary>
    public static Vector2 SizeOf(string sprite)
    {
        foreach (Template t in Templates)
            if (t.sprite == sprite) return t.size;
        return Vector2.zero;
    }

    // -------------------------------------------------------------------------

    /// <summary>
    /// Plans the next chunk continuing from <paramref name="entry"/> traveling
    /// <paramref name="headingIn"/>. Deterministic per seed. May turn 90° along
    /// a painted curve — never against <paramref name="forwardAxis"/>, and it
    /// steers back after a lateral leg. Avoids repeating any sprite used in the
    /// last few chunks and avoids overlapping already placed chunks.
    /// </summary>
    public static SceneChunkPlan PlanChunk(Vector2 entry, Vector2 headingIn, Vector2 forwardAxis,
                                           IList<ScenePlacement> existing, bool forceStraight,
                                           int seed, int order)
    {
        Vector2 dIn = Cardinal(headingIn);
        Vector2 fwd = Cardinal(forwardAxis.sqrMagnitude > 0.01f ? forwardAxis : Vector2.up);

        var exitDirs = new List<Vector2>();
        bool lateral = Mathf.Abs(Vector2.Dot(dIn, fwd)) < 0.5f;
        int roll = Hash(seed, 5) % 100;
        if (forceStraight) exitDirs.Add(dIn);
        else if (lateral)
        {
            if (roll < 80) { exitDirs.Add(fwd); exitDirs.Add(dIn); }
            else           { exitDirs.Add(dIn); exitDirs.Add(fwd); }
        }
        else
        {
            // Turn-heavy town core, opening into longer straight runs the
            // further the player drives: the turn chance decays with the
            // chunk order (~65% on the first chunks → ~25% past chunk 14).
            Vector2 side = (Hash(seed, 7) % 2 == 0) ? Perp(dIn) : -Perp(dIn);
            int turnPct = Mathf.RoundToInt(Mathf.Lerp(65f, 25f, Mathf.Clamp01(order / 14f)));
            if (roll >= turnPct) { exitDirs.Add(dIn); exitDirs.Add(side); }
            else                 { exitDirs.Add(side); exitDirs.Add(dIn); }
        }
        exitDirs.Add(dIn);   // safety net

        var recent = new HashSet<string>();
        if (existing != null)
            for (int i = Mathf.Max(0, existing.Count - NoRepeatWindow); i < existing.Count; i++)
                recent.Add(existing[i].sprite);

        SceneChunkPlan firstValid = null;
        foreach (Vector2 dOut in exitDirs)
        {
            if (Vector2.Dot(dOut, fwd) < -0.5f) continue;

            var candidates = new List<Template>();
            foreach (Template t in Templates)
                if (HasTransition(t, -dIn, dOut)) candidates.Add(t);
            if (candidates.Count == 0) continue;

            // prefer non-recent sprites; when the whole pool is recent, at
            // least never place the same sprite twice in a row
            var fresh = candidates.FindAll(t => !recent.Contains(t.sprite));
            var pool = fresh.Count > 0 ? fresh : candidates;
            if (fresh.Count == 0 && existing != null && existing.Count > 0 && candidates.Count > 1)
            {
                string last = existing[existing.Count - 1].sprite;
                var notLast = candidates.FindAll(t => t.sprite != last);
                if (notLast.Count > 0) pool = notLast;
            }

            int pick = Hash(seed, 11) % pool.Count;
            for (int k = 0; k < pool.Count; k++)
            {
                Template t = pool[(pick + k) % pool.Count];
                SceneChunkPlan plan = Compose(t, entry, dIn, dOut, seed, order);
                if (firstValid == null) firstValid = plan;
                if (!Collides(plan.placement, existing)) return plan;
            }
        }
        return firstValid;   // boxed in: accept the overlap (dither hides it)
    }

    /// <summary>
    /// Plans the initial town from <paramref name="start"/> along
    /// <paramref name="heading"/> covering <paramref name="targetLength"/>:
    /// a straight opening chunk, then turn-heavy streets (the same order-decay
    /// cadence as streaming, so the town core winds and later roads run long).
    /// Every choice depends only on the chunk index — NEVER the seed — so a
    /// level's starting town (and its story anchors) is identical across seeds.
    /// </summary>
    public static List<SceneChunkPlan> PlanInitial(Vector2 start, Vector2 heading,
                                                   float targetLength, int seed)
    {
        var plans = new List<SceneChunkPlan>();
        var placed = new List<ScenePlacement>();
        Vector2 pos = start;
        Vector2 fwd = Cardinal(heading);
        Vector2 dir = fwd;
        float covered = 0f;
        int order = 0;
        while (covered < targetLength || plans.Count == 0)
        {
            SceneChunkPlan p = PlanChunk(pos, dir, fwd, placed, forceStraight: order == 0,
                                         Hash(1237, order), order);
            if (p == null) break;
            plans.Add(p);
            placed.Add(p.placement);
            // progress counts along the level's forward axis, so lateral legs
            // wind the town without shortening it
            covered += Mathf.Max(0f, Vector2.Dot(p.exit - pos, fwd));
            pos = p.exit;
            dir = p.exitHeading;
            order++;
            if (order > 16) break;
        }
        return plans;
    }

    // -------------------------------------------------------------------------

    static bool HasPort(Template t, Vector2 side)
    {
        return !float.IsNaN(Port(t, side).x);
    }

    static bool HasTransition(Template t, Vector2 entrySide, Vector2 exitSide)
    {
        if (!HasPort(t, entrySide) || !HasPort(t, exitSide)) return false;
        if (t.allow == null || t.allow.Length == 0) return true;

        string code = SideCode(entrySide) + SideCode(exitSide);
        for (int i = 0; i < t.allow.Length; i++)
            if (t.allow[i] == code) return true;
        return false;
    }

    static Transition FindTransition(Template t, Vector2 entrySide, Vector2 exitSide)
    {
        string code = SideCode(entrySide) + SideCode(exitSide);
        if (t.transitions == null) return null;
        for (int i = 0; i < t.transitions.Length; i++)
            if (t.transitions[i].code == code) return t.transitions[i];
        return null;
    }

    static string SideCode(Vector2 side)
    {
        if (side.y > 0.5f) return "N";
        if (side.y < -0.5f) return "S";
        if (side.x > 0.5f) return "E";
        return "W";
    }

    static Vector2 Port(Template t, Vector2 side)
    {
        if (side.y > 0.5f)  return t.northPort;
        if (side.y < -0.5f) return t.southPort;
        if (side.x > 0.5f)  return t.eastPort;
        return t.westPort;
    }

    static SceneChunkPlan Compose(Template t, Vector2 entry, Vector2 dIn, Vector2 dOut,
                                  int seed, int order)
    {
        Vector2 pIn = Port(t, -dIn);
        Vector2 pOut = Port(t, dOut);
        Vector2 center = entry - pIn - dIn * (Overlap * 0.5f);
        Vector2 exit = center + pOut - dOut * (Overlap * 0.5f);

        var plan = new SceneChunkPlan
        {
            placement = new ScenePlacement { sprite = t.sprite, center = center, order = order },
            exit = exit,
            exitHeading = dOut,
        };

        bool turning = Mathf.Abs(Vector2.Dot(dIn, dOut)) < 0.5f;
        if (turning)
        {
            Transition transition = FindTransition(t, -dIn, dOut);
            Vector2 nsPort = Mathf.Abs(dIn.y) > 0.5f ? pIn : pOut;
            Vector2 ewPort = Mathf.Abs(dIn.y) > 0.5f ? pOut : pIn;
            Vector2 corner = center + (transition != null
                ? transition.graphCorner
                : new Vector2(nsPort.x, ewPort.y));
            plan.vertices.Add(corner);
            plan.corners.Add(true);

            if (transition != null && transition.path != null && transition.path.Length > 1)
            {
                Vector2 prev = entry;
                // First sample is the template port, represented by entry after
                // seam overlap. Consume the remaining explicit audited samples.
                for (int i = 1; i < transition.path.Length - 1; i++)
                {
                    Vector2 p = center + transition.path[i];
                    plan.drivePath.Add(p);
                    plan.extraSegments.Add(new RoadSegment(prev, p, true));
                    prev = p;
                }
                plan.extraSegments.Add(new RoadSegment(prev, exit, true));
            }
            else
            {
                plan.drivePath.Add(corner);
            }
        }
        else
        {
            // Straight pass: 1-2 boardable interior stops, clear of the ports.
            float len = Vector2.Distance(entry, exit);
            Vector2 dirN = (exit - entry) / Mathf.Max(len, 0.01f);
            if (len > 22f)
            {
                // Stops sit in the 0.28-0.36 / 0.64-0.72 windows — never near
                // mid-chunk, where the T/4-way painted into most scenes
                // crosses (a stop sign in the middle of a junction reads broken).
                int count = len > 44f ? 1 + Hash(seed, 41) % 2 : 1;
                for (int i = 0; i < count; i++)
                {
                    float f;
                    if (count == 1)
                        f = (Hash(seed, 47) % 2 == 0 ? 0.28f : 0.64f)
                            + (Hash(seed, 43) % 5) * 0.02f;
                    else
                        f = i == 0 ? 0.30f : 0.70f;
                    Vector2 v = entry + dirN * Mathf.Clamp(len * f, 9f, len - 9f);
                    plan.vertices.Add(v);
                    plan.corners.Add(false);
                    plan.drivePath.Add(v);
                }
            }
        }

        plan.vertices.Add(exit);
        plan.corners.Add(false);
        plan.drivePath.Add(exit);
        return plan;
    }

    static bool Collides(ScenePlacement p, IList<ScenePlacement> existing)
    {
        if (existing == null) return false;
        Vector2 size = SizeOf(p.sprite);
        var r = new Rect(p.center - size * 0.5f + Vector2.one * 2f, size - Vector2.one * 4f);
        foreach (ScenePlacement e in existing)
        {
            Vector2 es = SizeOf(e.sprite);
            var er = new Rect(e.center - es * 0.5f + Vector2.one * 2f, es - Vector2.one * 4f);
            if (r.Overlaps(er)) return true;
        }
        return false;
    }

    /// <summary>
    /// Rebinds authored story anchors onto the planned trunk: each anchor keeps
    /// its arc fraction along the route but moves to the nearest planned vertex,
    /// preserving name, kind and story order. With the seed-stable initial chain
    /// the resulting positions are identical for every seed.
    /// </summary>
    public static AnchorNode[] RemapAnchors(AnchorNode[] anchors, Vector2[] authoredTrunk,
                                            Vector2[] plannedTrunk)
    {
        if (anchors == null || anchors.Length == 0 || plannedTrunk == null || plannedTrunk.Length < 2)
            return anchors;

        float authoredLen = PolylineLength(authoredTrunk);
        float plannedLen = PolylineLength(plannedTrunk);
        var used = new HashSet<int>();
        var result = new AnchorNode[anchors.Length];

        for (int i = 0; i < anchors.Length; i++)
        {
            AnchorNode a = anchors[i];
            float frac;
            if (a.kind == AnchorKind.TerminalStart) frac = 0f;
            else if (a.kind == AnchorKind.TerminalEnd) frac = 1f;
            else if (authoredLen > 0.01f) frac = Mathf.Clamp01(ArcAlong(authoredTrunk, a.position) / authoredLen);
            else frac = 0.5f;

            int best = NearestVertex(plannedTrunk, frac * plannedLen, used);
            used.Add(best);
            result[i] = new AnchorNode { name = a.name, kind = a.kind, position = plannedTrunk[best] };
        }
        return result;
    }

    // -------------------------------------------------------------------------

    static Vector2 Cardinal(Vector2 v)
    {
        return Mathf.Abs(v.x) >= Mathf.Abs(v.y)
            ? new Vector2(Mathf.Sign(v.x), 0f)
            : new Vector2(0f, Mathf.Sign(v.y));
    }

    static Vector2 Perp(Vector2 v) => new Vector2(-v.y, v.x);

    static float PolylineLength(Vector2[] pts)
    {
        float len = 0f;
        for (int i = 1; i < pts.Length; i++) len += Vector2.Distance(pts[i - 1], pts[i]);
        return len;
    }

    static float ArcAlong(Vector2[] pts, Vector2 p)
    {
        float best = float.MaxValue, bestArc = 0f, arc = 0f;
        for (int i = 1; i < pts.Length; i++)
        {
            Vector2 a = pts[i - 1], b = pts[i];
            Vector2 ab = b - a;
            float t = ab.sqrMagnitude < 1e-4f ? 0f
                : Mathf.Clamp01(Vector2.Dot(p - a, ab) / ab.sqrMagnitude);
            Vector2 c = a + ab * t;
            float d = (c - p).sqrMagnitude;
            if (d < best) { best = d; bestArc = arc + ab.magnitude * t; }
            arc += ab.magnitude;
        }
        return bestArc;
    }

    static int NearestVertex(Vector2[] pts, float targetArc, HashSet<int> used)
    {
        float arc = 0f, bestDiff = float.MaxValue;
        int best = 0;
        for (int i = 0; i < pts.Length; i++)
        {
            if (i > 0) arc += Vector2.Distance(pts[i - 1], pts[i]);
            if (used.Contains(i)) continue;
            float diff = Mathf.Abs(arc - targetArc);
            if (diff < bestDiff) { bestDiff = diff; best = i; }
        }
        return best;
    }

    static int Hash(int seed, int salt)
    {
        unchecked
        {
            int h = (int)2166136261;
            h = (h ^ seed) * 16777619;
            h = (h ^ salt) * 16777619;
            return h & 0x7fffffff;
        }
    }
}
